# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all 
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
ENABLE_LINTERS: KOTLIN_KTLINT, GIT_GIT_DIFF
KOTLIN_KTLINT_ARGUMENTS: --disabled_rules no-wildcard-imports
