# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all 
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
ENABLE: kotlin
